### ISSUE TITLE
mod uploading is entirely broken

### ISSUE THREAD

**Issue by abso1utezer0** [KjubDusJub/Epic-Mickey-Launcher#11]
on latest version, i have spent the last 4 hours trying to upload a mod and i can only assume at this point that there is some issue with the server

everything is set up perfectly
![image](https://github.com/user-attachments/assets/a36f3777-7ebc-4b2f-ba5d-9ec59f636dac)

**Comment by kalsvik** [comment]
Looking at the name of the mod, i can assume there is probably a DLL in the mod and we don't allow dlls yet.

I believe the server return message redacts why your mod was denied for security reasons although I frankly don't know what I wrote.

In the case you don't have a DLL, EXE, SCR, or any other executable/codeloading file, send a reply.

**Comment by kalsvik** [comment]
Also, send the mod repository as I don't see it on your public GitHub.

**Comment by abso1utezer0** [comment]
> Looking at the name of the mod, i can assume there is probably a DLL in the mod and we don't allow dlls yet.
> 
> I believe the server return message redacts why your mod was denied for security reasons although I frankly don't know what I wrote.
> 
> In the case you don't have a DLL, EXE, SCR, or any other executable/codeloading file, send a reply.

I'm a little confused

I've previously uploaded a mod (Renexus) which is currently on the market and contains a DLL (redistributes Ultimate ASI Loader)

Also, this mod doesn't contain a DLL (plugin is technically of the DLL type but uses the ASI extension so it would only get loaded if the user already has an ASI loader installed for the game). I had a feeling this would be an issue so I simply included instructions in the description to install an ASI loader of sorts into the game's base folder.

**Comment by abso1utezer0** [comment]
> Also, send the mod repository as I don't see it on your public GitHub. 

I had it on GitLab but I'll upload it on here when I get the time

**Comment by abso1utezer0** [comment]
I looked at the validation code and yeah it shouldn't be getting flagged to my knowledge (there are no files with the "banned" extensions).

**Comment by kalsvik** [comment]
> I've previously uploaded a mod (Renexus) which is currently on the market and contains a DLL (redistributes Ultimate ASI Loader)
>
Your mod was uploaded before eml-validate was put in prod
> Also, this mod doesn't contain a DLL (plugin is technically of the DLL type but uses the ASI extension so it would only get loaded if the user already has an ASI loader installed for the game). I had a feeling this would be an issue so I simply included instructions in the description to install an ASI loader of sorts into the game's base folder.
>
Then your mod shouldnt be getting flagged. It may have something to do with the sql query, I will look into it.

**Comment by abso1utezer0** [comment]
If you are worried about people executing malicious code then I don't think DLLs are at the head of that issue

I've been able to inject assembly code just by screwing with pointers in different formats (specifically packfiles)

Not sure how you would go about implementing security with such a broad issue but you might want to have your validation code verify that the formats aren't screw-y as well if that is your intent

**Comment by abso1utezer0** [comment]
> 
> > I've previously uploaded a mod (Renexus) which is currently on the market and contains a DLL (redistributes Ultimate ASI Loader)
> >
> Your mod was uploaded before eml-validate was put in prod
> > Also, this mod doesn't contain a DLL (plugin is technically of the DLL type but uses the ASI extension so it would only get loaded if the user already has an ASI loader installed for the game). I had a feeling this would be an issue so I simply included instructions in the description to install an ASI loader of sorts into the game's base folder.
> >
> Then your mod shouldnt be getting flagged. It may have something to do with the sql query, I will look into it.
> 
> 
> 

With the information I now have I can confidently call this a lie. Just tell me I'm banned bro. Lmfao

You can say it's not a ban but instituting an EML Big Brother based of a goofy troll your dog got fed might as well just be a banning of me

**Comment by abso1utezer0** [comment]
👃

**Comment by abso1utezer0** [comment]
hello andrew

**Comment by abso1utezer0** [comment]
hoovie send me a friend request :D
I have some things to tell you

**Comment by abso1utezer0** [comment]
i can still see you mugs

**Comment by abso1utezer0** [comment]
i know about your mole too, ive been feeding him false information

**Comment by abso1utezer0** [comment]
K-Day further approaches

Your thoughts of it entails are incorrect

**Comment by abso1utezer0** [comment]
lol typo

**Comment by abso1utezer0** [comment]
road trip incoming

**Comment by abso1utezer0** [comment]
i particularly am drawn to the east coast

**Comment by abso1utezer0** [comment]
i would have to pick up nick first though he's in cali

**Comment by abso1utezer0** [comment]
we've actually been saving up a bit of a fund for travel expenses and ive been grinding at work so we've got the funds i think

**Comment by abso1utezer0** [comment]
and before you try some goonery - no, you cannot sue me for existing near you (though i am sure you will try)

**Comment by abso1utezer0** [comment]
bro gonna tell his madre about el koopy

**Comment by abso1utezer0** [comment]
> i would have to pick up nick first though he's in cali 

not pick him up he's flying in lol

**Comment by abso1utezer0** [comment]
would have to drive the length of the entire country and I am not doing that for a troll

**Comment by abso1utezer0** [comment]
me and eddd and tempest are meeting up in Chicago though

**Comment by abso1utezer0** [comment]
the most humorous idea would be a tour but there aren't enough americans in

**Comment by abso1utezer0** [comment]
@pleasantgr8ient if you play me in a first to three game of fortnite zone wars and win i will concede

**Comment by abso1utezer0** [comment]
that's why i was gone during summer 2022

**Comment by abso1utezer0** [comment]
the lead admin was a public gooner and watched over a community of children (like thatguy_luigi) and it made me uncomfortable so i left

**Comment by abso1utezer0** [comment]
still friends with the creator though

**Comment by abso1utezer0** [comment]
openem will not exist by my birthday

**Comment by abso1utezer0** [comment]
https://youtu.be/6H8ouf_m9hQ

**Comment by abso1utezer0** [comment]
function point will not exist by my birthday

**Comment by abso1utezer0** [comment]
what percentage of your servers population is me

**Comment by abso1utezer0** [comment]
You can't have a server dedicated to stalking me and then be surprised when I strike back

The mysterious shit doesn't work brother I do not care

**Comment by kalsvik** [comment]
frankly you should be, and your little stunt here only proves that moreso, but you are in fact not banned.
