### ISSUE TITLE
mod path error

### ISSUE THREAD

**Issue by abso1utezer0** [KjubDusJub/Epic-Mickey-Launcher#4]
Steps:

1. Open a fresh version of the EML
2. Go to download/install the EMBA mod
3. Deny any requests for files. The program should say "Mod Installed!" or something similar.
4. An exception is thrown.

I know most users probably wont encounter this but a check for if the mod actually successfully installed should be implemented. Then a message like "Install Failed! No game files provided. Try to redownload the game from the main menu." could show.

**Comment by KjubDusJub** [comment]
this has already been fixed in a updated version which im releasing now
