### ISSUE TITLE
Windows Defender blocked a Trojan?

### ISSUE THREAD

**Issue by SkylarPlayz348** [KjubDusJub/Epic-Mickey-Launcher#8]
I was downloading NKIT and got this 
![image](https://github.com/KjubDusJub/Epic-Mickey-Launcher/assets/73512621/a50e4cf8-db27-4440-8d40-6685ffb1bccf)

**Comment by kalsvik** [comment]
False positive.

**Comment by SkylarPlayz348** [comment]
Ik this is closed but it may not be a trojan but i had to reinstall windows after installing this (luckily i kept my files). My C: drive was at 100% about 99% of the time and my pc was unusable for at least 36 hrs(some of that was recovery).

**Comment by kalsvik** [comment]
That is really strange. Discord removed the download link for NKit a little before you had that issue, so I have no idea what that is. Anyway, NKit has now become obsolete and will be removed from EML now that it is not needed anymore.
